<?php
/**
 * Created by PhpStorm.
 * User: anget
 * Date: 19.07.16
 * Time: 14:10
 */

namespace Boboyan\ContentBundle\ImageProcessor;


class GAppsImageProcessor extends ImageProcessor
{
    // данные проекта из google console
    const PROJECT_NAME = null;
    const CLIENT_ID = null;
    const CLIENT_SECRET = null;
    const DEVSTORAGE_URL = 'https://www.googleapis.com/auth/devstorage.full_control';

    public function store($image)
    {
        $client = new \Google_Client();

        $client->setApplicationName(self::PROJECT_NAME);
        $client->setClientId(self::CLIENT_ID);
        $client->setClientSecret(self::CLIENT_SECRET);
        //$redirect_uri = 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF'];
        //$client->setRedirectUri($redirect_uri);
        $client->setScopes(self::DEVSTORAGE_URL);
        $privateKey = file_get_contents('bobo-8acfe899b840.p12'); // получаем контент .p12 файла, который получили ранее
        $client->setAssertionCredentials(new \Google_Auth_AssertionCredentials(
            'bobo-1379@appspot.gserviceaccount.com', // имеет вид 12345678910-fb2vu7ipertbg3t73shtu2m30b838756@developer.gserviceaccount.com, получили ранее
            array(self::DEVSTORAGE_URL),
            $privateKey
        ));

        $storageService = new \Google_Service_Storage($client);
        $objects = $storageService->objects;

        $object = new \Google_Service_Storage_StorageObject();
        $object->setName($image); // имя файла в bucket(на диске google)
        $res = $objects->insert(
            'bobo-1379.appspot.com', $object, array(
                'data' => file_get_contents(realpath('').'/upload/images_small/test.jpeg'), // контент файла
                'uploadType' => 'media',
                //'contentEncoding' => CFileHelper::getMimeType('FILE_PATH'), // MIME-тип файла, в этом примере для этого используется класс CFileHelper из Yii2
                //'mimeType' => CFileHelper::getMimeType('FILE_PATH'), // то же самое, так же вы можете установить универсальный application/octet-stream
                'predefinedAcl' => 'publicread' // присваиваем предопределенный ACL public-read
            )
        );
        return $res;
    }

    public function delete()
    {
        parent::delete(); // TODO: Change the autogenerated stub
    }

    public function show()
    {
        // TODO: Implement show() method.
    }

}